language: objective-c
before_install:
  - cd xcode
  - brew update
  - brew upgrade xctool -> /dev/null
  - export LANG=en_US.UTF-8
  - gem install cocoapods
before_script:
  - export LANG=en_US.UTF-8
script: xctool -workspace SafeCast.xcworkspace -scheme SafeCast test -sdk iphonesimulator

